#! /usr/bin/env python
# encoding: utf-8

APPNAME = 'ubi'
VERSION = '0.1'

out = 'bin'

def options(opt):
  opt.load('compiler_cxx')

def configure(conf):
  conf.load('compiler_cxx')

def build(bld):
  bld.program(source='main.cpp', target='ubi')

def dist(ctx):
  ctx.algo = 'tar.gz'

